module.exports = {
  questions: [
    "types",
    "coercion",
    "scope",
    "closures",
    "modules",
    "currying",
    "objects",
    "immutability",
    "prototypes",
    "asynchrony",
    "callbacks",
    "promises",
    "performance",
    "dom",
    "strings",
    "arrays",
    "miscellaneous",
    "polyfill",
  ],
};
